name: CI-CD-to-AWS
env:
  S3_BUCKET_NAME      : ""
  APPLICATION_NAME    : ""
  ENVIRONMENT_NAME    : ""
  DEPLOY_PACKAGE_NAME : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME     : ""

on: 
  push:
    branches:
      - main

jobs:
  ci_part:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Git clone repo
      uses: actions/checkout@v1
    - name: Create zip package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
